### ISSUE TITLE
Add exemplary programs

### ISSUE THREAD

**Issue by resolritter** [typedbyte/effet#1]
The [capability library](https://github.com/tweag/capability) has [multiple examples](https://github.com/tweag/capability/tree/master/examples) of single-file programs. This library, on the other hand, walks through a sample implementation in the README, but has no example programs; it would be nicer to have a whole example laid out in a single file instead of having to stitch together the README's code in order to run it.

**Comment by typedbyte** [comment]
Yes, I agree. I think this coincides with the need for more tests in general. I tested all the code on simple examples and some not-so-simple examples, but this is mostly undocumented. Time to bring more structure into the process, I will see what I can do.

**Comment by typedbyte** [comment]
I added some examples and tests in the "examples" folder.

**Comment by resolritter** [comment]
Thanks! I'll make some time to check them later and give some feedback here if relevant.
